
-- ID 252
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuál es el horario de servicio en la Biblioteca?','El horario de servicio de la Biblioteca es de lunes a viernes de 7:00 a 21:00 horas. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx para recibir apoyo.','alumnos',true,'["horario biblioteca","a que hora abre biblioteca","horario biblioteca uttt","cuando abre biblioteca","horario de biblioteca","biblioteca horario uttt","a que hora cierra biblioteca","horario servicio biblioteca","horario biblioteca universidad","horario biblioteca estudiantes","cuando puedo ir a biblioteca","horario atencion biblioteca","biblioteca abierta horario","horario biblioteca campus","horario biblioteca lunes a viernes","biblioteca horario servicio","a que hora abre y cierra biblioteca","horario biblioteca alumnos","horario biblioteca escuela","horario biblioteca uttt estudiantes"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios'); 

-- ID 253
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Necesito alguna credencial para ingresar a la Biblioteca?','No necesitas una credencial física especial; sin embargo, debes registrarte en la entrada utilizando tus credenciales del sistema SIGE en el módulo de circulación. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx para recibir apoyo.','alumnos',true,'["necesito credencial biblioteca","puedo entrar sin credencial biblioteca","como entrar a biblioteca","requisitos para entrar biblioteca","credencial biblioteca uttt","puedo entrar biblioteca sin credencial","que necesito para entrar biblioteca","registro entrada biblioteca","como ingreso a biblioteca","necesito identificacion biblioteca","puedo entrar biblioteca libremente","requisitos biblioteca uttt","entrada biblioteca requisitos","como registrarme en biblioteca","acceso biblioteca estudiantes","puedo entrar biblioteca sin tarjeta","como funciona entrada biblioteca","credencial obligatoria biblioteca","ingreso biblioteca uttt","registro biblioteca entrada"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');



-- ID 254
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo ingresar a la Biblioteca con bolso o mochila?','No, no está permitido ingresar con bolsos o mochilas. Debes resguardarlos en el área de paquetería o lockers ubicados en la entrada de la Biblioteca. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx para recibir apoyo.','alumnos',true,'["puedo entrar con mochila biblioteca","bolsas en biblioteca permitidas","puedo llevar mochila biblioteca","permiten mochilas biblioteca","puedo entrar con bolso biblioteca","reglas mochila biblioteca","donde dejar mochila biblioteca","lockers biblioteca uttt","paqueteria biblioteca","puedo entrar con bolsa biblioteca","restricciones biblioteca mochila","mochila biblioteca permitido","donde guardar mochila biblioteca","puedo entrar con mochila uttt","reglas biblioteca mochila","puedo llevar bolso biblioteca","uso lockers biblioteca","paqueteria biblioteca reglas","puedo ingresar con mochila","biblioteca mochila reglas"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');


-- ID 255
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo dejar mis cosas en paquetería o lockers y salir de la Biblioteca?','No, el uso del área de paquetería y lockers es únicamente durante tu estancia dentro de la Biblioteca, por lo que no está permitido dejar tus pertenencias y retirarte. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx para recibir apoyo.','alumnos',true,'["puedo dejar cosas en lockers y salir","lockers biblioteca reglas","puedo salir y dejar mochila biblioteca","uso lockers biblioteca condiciones","puedo dejar mochila y salir biblioteca","paqueteria biblioteca uso","reglas lockers biblioteca","puedo dejar cosas biblioteca","lockers biblioteca tiempo uso","puedo salir y regresar lockers","uso correcto lockers biblioteca","puedo dejar mochila biblioteca y salir","condiciones paqueteria biblioteca","lockers biblioteca restricciones","puedo usar lockers y salir","reglas uso lockers biblioteca","puedo guardar cosas biblioteca","paqueteria biblioteca uso permitido","lockers biblioteca permanencia","puedo dejar cosas sin estar biblioteca"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');

-- ID 256
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo ingresar a la Biblioteca con alimentos o bebidas?','No, no está permitido ingresar con alimentos ni bebidas a la Biblioteca. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx para recibir apoyo.','alumnos',true,'["puedo comer en biblioteca","puedo llevar comida biblioteca","permiten alimentos biblioteca","puedo beber en biblioteca","comida en biblioteca permitido","bebidas en biblioteca","reglas alimentos biblioteca","puedo entrar con comida biblioteca","puedo tomar bebidas biblioteca","alimentos biblioteca reglas","esta permitido comer biblioteca","puedo llevar snacks biblioteca","bebidas permitidas biblioteca","comer dentro biblioteca","reglas comida biblioteca","puedo entrar con bebida biblioteca","prohibido comida biblioteca","puedo comer dentro biblioteca","alimentos en biblioteca uttt","bebidas en biblioteca uttt"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');

-- ID 257
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo solicitar libros para préstamo a domicilio?','Sí, puedes solicitar hasta 3 libros a domicilio, siempre que sean títulos diferentes. Te recomendamos verificar tu fecha de entrega para evitar inconvenientes. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx para recibir apoyo.','alumnos',true,'["prestamo libros domicilio","puedo llevar libros a casa","cuantos libros puedo pedir","prestamo biblioteca domicilio","libros a casa biblioteca","prestamo libros uttt","cuantos libros puedo llevar biblioteca","prestamo a domicilio biblioteca","puedo sacar libros biblioteca","libros prestamo domicilio uttt","cuantos prestamos puedo hacer","libros biblioteca a casa","prestamo libros reglas","puedo llevar libros biblioteca","limite libros prestamo","prestamo domicilio reglas","libros prestados cuantos","prestamo biblioteca limite","puedo sacar 3 libros biblioteca","reglas prestamo libros"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');

-- ID 258
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Por cuántos días puedo tener un libro en préstamo a domicilio?','En libros de conocimientos técnicos, el préstamo es por 3 días hábiles, y en libros de literatura general es por 15 días hábiles. Te recomendamos verificar tu fecha de entrega para evitar inconvenientes. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx o al teléfono 773 732 9100 ext. 454 y 144 para recibir apoyo.','alumnos',true,'["dias prestamo libros","cuanto tiempo puedo tener libro","prestamo biblioteca dias","tiempo prestamo libros uttt","dias prestamo domicilio","cuanto dura prestamo biblioteca","dias libros biblioteca","prestamo tecnico dias","prestamo literatura dias","tiempo libros prestados","dias maximos prestamo","cuanto dura libro prestado","dias biblioteca prestamo","tiempo devolucion libros","prestamo dias universidad","libros cuantos dias prestamo","duracion prestamo libros","dias permitidos libros","tiempo limite prestamo","cuanto tiempo puedo tener libros"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios'); 

-- ID 259
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo renovar el préstamo de un libro?','Sí, puedes renovar el préstamo de tus libros hasta 3 veces. Te recomendamos realizar la renovación antes de la fecha de vencimiento para evitar inconvenientes. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx o al teléfono 773 732 9100 ext. 454 y 144 para recibir apoyo.','alumnos',true,'["puedo renovar libros","renovar prestamo biblioteca","cuantas veces renovar libros","renovacion libros uttt","puedo extender prestamo libros","renovar libros biblioteca","cuantas renovaciones puedo hacer","renovacion prestamo domicilio","puedo renovar libro prestado","renovar libros cuantas veces","extension prestamo libros","renovar libros universidad","puedo renovar libros uttt","renovacion libros reglas","cuantas veces renovar biblioteca","renovacion prestamo biblioteca","puedo renovar libro varias veces","renovacion libros domicilio","extender tiempo libros","renovar libros permitido"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');

-- ID 260
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo renovar mis libros vía telefónica?','Sí, puedes renovar tu préstamo a domicilio mediante llamada telefónica, siempre y cuando lo hagas dentro del horario de servicio. Puedes comunicarte al teléfono 773 732 9100 ext. 454 y 144. Te recomendamos realizar la renovación antes de la fecha de vencimiento para evitar inconvenientes. Si tienes alguna duda, también puedes escribir al correo biblioteca@uttt.edu.mx.','alumnos',true,'["renovar libros telefono","puedo renovar libros por telefono","renovacion telefonica biblioteca","telefono renovar libros","puedo llamar para renovar libros","renovar prestamo por telefono","numero biblioteca renovar libros","extensiones biblioteca renovar","renovar libros llamada","puedo renovar libros sin ir","renovacion remota libros","telefono biblioteca renovacion","llamar para renovar libros","renovar libros sin ir biblioteca","renovacion telefonica uttt","puedo renovar libros llamando","extensiones biblioteca","renovacion via telefono","numero renovacion libros","telefono biblioteca uttt"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');

-- ID 261
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Hay multa por no devolver un libro a tiempo?','Sí, el Sistema Gestor de Bibliotecas genera una multa por devolución extemporánea de $16.00 por día y por libro. Te recomendamos verificar tu fecha de entrega para evitar cargos adicionales. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx o al teléfono 773 732 9100 ext. 454 y 144 para recibir apoyo.','alumnos',true,'["multa biblioteca","cuanto cuesta multa biblioteca","multa por retraso libros","no devolvi libro multa","cuanto cobran por retraso libros","multa biblioteca uttt","penalizacion libros biblioteca","cuanto es multa por libro","multa diaria biblioteca","costo retraso libros","multa por no devolver libro","cuanto debo pagar biblioteca","multa libros retraso","penalizacion biblioteca libros","cuanto cuesta multa diaria","multa libros universidad","costo multa biblioteca","retraso devolucion libros multa","multa por dia libro","cuanto es multa biblioteca"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');


-- ID 262
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué pasa si daño o pierdo un libro de la Biblioteca?','En caso de extravío, daño o deterioro de un libro, deberás reponerlo en calidad de nuevo. Te recomendamos cuidar el material durante su uso para evitar inconvenientes. Si tienes alguna duda, puedes comunicarte al correo biblioteca@uttt.edu.mx o al teléfono 773 732 9100 ext. 454 y 144 para recibir apoyo.','alumnos',true,'["perdi libro biblioteca","dañe libro biblioteca","que pasa si pierdo libro","reponer libro biblioteca","multa por perder libro","libro dañado biblioteca","que hago si pierdo libro","reemplazo libro biblioteca","perdi libro que hago","daño libro biblioteca solucion","reponer libro uttt","libro extraviado biblioteca","que pasa si rompo libro","reposicion libro biblioteca","libro mojado biblioteca","perdida libro biblioteca","que hacer libro dañado","reposicion libros biblioteca","perder libro universidad","dañar libro biblioteca consecuencias"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');  

-- ID 263
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Dónde está la Biblioteca de la UTTT?','La Biblioteca se encuentra dentro del campus Tula-Tepeji de la UTTT. Está ubicada en la zona central, cerca de la cafetería y de la Unidad de Docencia (UD3). Puedes consultar el croquis del campus en el siguiente enlace: https://www.uttt.edu.mx/Micrositio/croquis/','alumnos',true,'["donde esta la biblioteca","ubicacion biblioteca uttt","donde queda biblioteca","como llegar a biblioteca uttt","biblioteca donde esta","ubicacion biblioteca campus","donde esta biblioteca universidad","biblioteca uttt ubicacion","como ubicar biblioteca","donde esta biblioteca tula tepeji","mapa biblioteca uttt","donde queda biblioteca uttt","ubicacion biblioteca universidad","como llegar biblioteca campus","biblioteca en el mapa uttt","donde esta biblioteca ud3","ubicacion biblioteca escuela","como encontrar biblioteca uttt","biblioteca campus ubicacion","donde esta biblioteca en el campus"]'::jsonb,'René Abisaí Aguilar Bravo','Jefe (a) de departamento','Departamento de Servicios Bibliotecarios');

-- ID 264
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿La universidad cuenta con Servicio Médico?','Sí, la universidad cuenta con un Servicio Médico que brinda orientación en salud, atención básica y actividades de prevención para estudiantes y personal.','aspirantes',true,'["hay servicio medico uttt","tienen medico en la universidad","servicio medico universidad uttt","hay enfermeria uttt","atencion medica universidad","hay clinica en uttt","servicio de salud uttt","hay doctor en la universidad","servicio medico disponible uttt","uttt tiene servicio medico","hay enfermeria en la escuela","servicio medico campus","atencion medica uttt","salud universidad uttt","hay medico campus uttt","servicio medico estudiantes","universidad tiene medico","servicio medico disponible","atencion salud uttt","hay servicio salud universidad"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 265
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Los aspirantes pueden recibir atención médica en la universidad?','Durante procesos de admisión o actividades dentro del campus, puedes acudir al Servicio Médico para recibir primeros auxilios y orientación en caso de malestar o emergencia.','aspirantes',true,'["aspirantes pueden usar servicio medico","puedo ir al medico siendo aspirante","atencion medica aspirantes uttt","puedo usar enfermeria aspirante","servicio medico para aspirantes","hay medico para aspirantes","puedo acudir al medico en admision","atencion medica proceso admision","aspirantes pueden recibir atencion","servicio medico examen admision","puedo ir a enfermeria aspirante","atencion salud aspirantes","servicio medico durante examen","puedo acudir servicio medico aspirante","atencion medica campus aspirante","aspirantes servicio salud","puedo usar servicio medico admision","atencion medica universidad aspirante","servicio medico disponible aspirantes","puedo recibir primeros auxilios aspirante"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 266
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Dónde se encuentra el Servicio Médico?','El Servicio Médico se encuentra en el Campus Tula-Tepeji, en la planta alta del edificio UD3. El horario de atención es de lunes a viernes de 07:00 a 21:00 horas.','alumnos',true,'["donde esta servicio medico","ubicacion servicio medico uttt","donde queda enfermeria","servicio medico donde esta","ubicacion medico campus","donde encontrar servicio medico","enfermeria ubicacion uttt","servicio medico ud3","donde esta enfermeria uttt","ubicacion servicio salud","como llegar servicio medico","donde esta medico universidad","servicio medico campus ubicacion","enfermeria campus donde","donde esta ud3 medico","ubicacion servicio medico escuela","donde esta area medica","servicio medico direccion","como ubicar servicio medico","ubicacion enfermeria universidad"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 267
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué tipo de atención brinda el Servicio Médico?','El Servicio Médico ofrece consulta médica general, atención de enfermería, toma de signos vitales, primeros auxilios y orientación en temas de salud.','alumnos',true,'["que servicios da servicio medico","que atienden en enfermeria","servicios medico uttt","que hace servicio medico","atencion enfermeria uttt","consulta medica universidad","servicios salud campus","que incluye servicio medico","atencion medica que ofrecen","servicio medico que hace","que atienden en servicio medico","tipo de atencion medica","servicios de salud universidad","que incluye enfermeria","consulta general uttt","servicio medico actividades","atencion medica estudiantes","servicios enfermeria universidad","que ofrece servicio salud","atencion basica medico"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');


-- ID 268
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Necesito cita para acudir al Servicio Médico?','No es necesario agendar cita. Puedes acudir directamente al Servicio Médico y serás atendido según el orden de llegada o la prioridad del caso.','alumnos',true,'["necesito cita servicio medico","puedo ir sin cita medico","cita enfermeria uttt","servicio medico con cita","puedo ir directo servicio medico","requiere cita medico universidad","puedo ir sin cita enfermeria","servicio medico sin cita","como acudir servicio medico","puedo ir directo al medico","cita servicio salud uttt","necesito agendar medico","puedo ir sin cita universidad","servicio medico acceso directo","atencion sin cita medico","puedo acudir sin cita","servicio medico turno","como funciona servicio medico","necesito registro medico","puedo ir directo enfermeria"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 269
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿El Servicio Médico proporciona medicamentos?','El Servicio Médico puede proporcionarte medicamentos básicos en una dosis inicial, de acuerdo con la valoración médica o de enfermería. No se otorgan tratamientos completos, por lo que, si es necesario, se te orientará para continuar la atención en una unidad de salud. Si tienes alguna duda, puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167 para recibir apoyo.','alumnos',true,'["dan medicamentos servicio medico","medicinas enfermeria uttt","me dan medicamentos universidad","servicio medico da medicinas","medicamento servicio medico","dan tratamiento completo medico","medicinas en enfermeria","servicio medico receta","me pueden dar medicina uttt","dan pastillas servicio medico","medicamentos basicos universidad","servicio medico tratamiento","dan medicamentos estudiantes","medicina en campus","servicio medico da recetas","me pueden dar medicamento","medicinas servicio salud","tratamiento medico universidad","dan medicina enfermeria","servicio medico medicacion"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 270
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué hago en una emergencia médica dentro de la universidad?','Debes avisar de inmediato a un docente, personal administrativo o acudir al Servicio Médico para recibir atención. Si es necesario, se activarán los protocolos de atención y traslado médico. Para apoyo adicional, puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167.','alumnos',true,'["emergencia medica que hago","que hacer si me siento mal escuela","emergencia universidad medico","primeros auxilios uttt","que hacer emergencia campus","me siento mal que hago","emergencia salud uttt","que hacer accidente universidad","servicio medico emergencia","a quien avisar emergencia","que hacer si me desmayo escuela","emergencia medica campus","que hacer si me siento mal uttt","ayuda medica universidad","protocolo emergencia uttt","que hacer accidente campus","servicio medico urgencia","emergencia estudiantes que hacer","primeros auxilios universidad","atencion emergencia uttt"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 271
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿El Servicio Médico realiza campañas de salud?','Sí, durante el año se realizan campañas de prevención y promoción de la salud, como vacunación, salud sexual, detección de enfermedades y fomento de estilos de vida saludables. Puedes enterarte de estas actividades a través de medios institucionales, redes sociales y avisos dentro del campus. Si tienes alguna duda, puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167.','alumnos',true,'["campañas de salud uttt","vacunacion universidad uttt","campañas servicio medico","eventos salud universidad","promocion salud uttt","campañas medicas universidad","salud sexual universidad uttt","deteccion enfermedades uttt","campañas enfermeria uttt","actividades salud campus","campañas vacunacion uttt","servicio medico campañas","programas salud universidad","eventos servicio medico","campañas bienestar uttt","prevencion salud universidad","campañas informativas salud","servicio medico actividades","eventos salud estudiantes","campañas universidad salud"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');


-- ID 272
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿El Servicio Médico puede emitir certificado médico para estadía?','Sí, el Servicio Médico puede realizar la valoración médica y emitir el certificado médico para estadía cuando sea solicitado. Este servicio no tiene costo. Para tramitarlo debes presentar tu credencial institucional, tu grupo sanguíneo comprobable (en licencia de manejo o resultados de laboratorio) y, en caso de que la convocatoria lo solicite, los resultados de antidoping. Si tienes alguna duda, puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167.','alumnos',true,'["certificado medico estadia","constancia medica estadia","puedo sacar certificado medico","servicio medico certificado","certificado medico universidad","requisitos certificado medico uttt","constancia medica estudiantes","certificado para estadia","servicio medico documento","certificado medico requisitos","puedo sacar constancia medica","certificado medico gratis","tramite certificado medico","certificado medico que necesito","servicio medico emite certificado","documento medico estadia","certificado medico campus","como sacar certificado medico","constancia medica uttt","certificado medico universidad requisitos"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 273
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Los estudiantes cuentan con IMSS?','Sí, los estudiantes inscritos pueden acceder al Seguro Facultativo del IMSS. Para iniciar el trámite debes descargar la aplicación IMSS Digital, consultar tu Número de Seguridad Social (NSS) y tu vigencia de derechos, y posteriormente acudir al Servicio Médico para completar el proceso de alta. Si tienes alguna duda, puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167.','alumnos',true,'["estudiantes tienen imss","seguro facultativo uttt","imss estudiantes uttt","tengo seguro imss universidad","como sacar imss estudiante","seguro medico estudiantes uttt","imss universidad proceso","seguro facultativo como tramitar","imss para estudiantes","seguro medico escuela","como obtener imss uttt","seguro estudiantes universidad","imss digital estudiantes","tramite imss uttt","seguro facultativo requisitos","como registrarme imss estudiante","imss universidad como funciona","seguro salud estudiantes","imss alta estudiantes","seguro facultativo universidad"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');


-- ID 274
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo puedo agendar mi primera cita en el área de Psicología?','Puedes solicitar tu primera cita directamente en el área de Psicología ubicada en la Biblioteca de la universidad o con tu tutor(a) de acompañamiento. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["agendar cita psicologia","como sacar cita psicologia","psicologia cita uttt","como ir a psicologia","cita psicologica universidad","como pedir apoyo psicologico","agendar terapia uttt","psicologia donde agendar","como sacar cita psicologo","quiero cita psicologia","psicologia contacto cita","agendar consulta psicologica","como pedir cita psicologia","psicologia estudiantes cita","quiero hablar con psicologo","cita psicologia campus","psicologia servicio cita","como acceder psicologia","cita apoyo emocional uttt","psicologia agendar sesion"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');

-- ID 275
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuánto dura una sesión en el área de Psicología?','Cada sesión tiene una duración aproximada de 50 minutos. Se recomienda tomar en cuenta este tiempo para que no afecte tu horario de clases, además de que el horario se te asigna al momento de tu cita. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["cuanto dura sesion psicologia","duracion terapia uttt","cuanto tiempo es consulta psicologica","duracion sesion psicologo","cuanto dura terapia","tiempo consulta psicologia","sesion psicologica cuanto dura","duracion apoyo psicologico","cuanto dura cita psicologia","tiempo sesion psicologo","duracion terapia estudiantes","cuanto dura consulta emocional","tiempo psicologia uttt","duracion consulta psicologica","cuanto tiempo psicologo","sesion terapia tiempo","duracion apoyo emocional","cuanto dura sesion terapia","consulta psicologica tiempo","cuanto dura cita psicologo"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');

-- ID 276
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿El servicio de Psicología tiene algún costo?','No te preocupes por eso, el servicio de atención psicológica es totalmente gratuito para todos los alumnos con inscripción vigente. Es parte de tu formación integral. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["psicologia cuesta","cuanto cuesta psicologia uttt","servicio psicologico gratis","psicologo gratis universidad","tiene costo psicologia","consulta psicologica precio","psicologia es gratis","cuanto cuesta terapia uttt","servicio psicologico costo","psicologia estudiantes costo","terapia gratis uttt","psicologia precio universidad","cuanto cuesta consulta psicologica","psicologo costo uttt","servicio emocional costo","psicologia sin costo","consulta psicologica gratis","psicologo gratis estudiantes","psicologia universidad costo","terapia costo uttt"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');

-- ID 277
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Hay consultas psicológicas en línea?','Sí, el área de Psicología cuenta con modalidad híbrida. Al momento de agendar tu cita podrás elegir entre una sesión presencial o en línea mediante videoconferencia, videollamada, llamada telefónica o WhatsApp. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["psicologia en linea","consulta psicologica online","psicologo virtual uttt","terapia en linea uttt","psicologia virtual estudiantes","consulta psicologica por telefono","psicologo por whatsapp","psicologia videollamada","consulta psicologica virtual","psicologia modalidad mixta","terapia online universidad","psicologo remoto uttt","consulta emocional online","psicologia llamada telefonica","apoyo psicologico virtual","psicologia por zoom","consulta psicologica whatsapp","terapia a distancia uttt","psicologia digital","psicologo en linea uttt"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');

-- ID 278
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Es confidencial lo que comparta en el área de Psicología?','Sí, tu proceso es totalmente confidencial. El personal académico, administrativo o tu familia no tienen acceso a tu expediente psicológico. Nos regimos bajo un código de ética profesional, por lo que todo lo que compartas es privado, a menos que exista un riesgo grave para tu integridad o la de terceros. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["es confidencial psicologia","privacidad psicologo","psicologia es privada","lo que diga psicologo se comparte","confidencialidad terapia","psicologo guarda secreto","privacidad consulta psicologica","psicologia privacidad uttt","confidencialidad estudiantes","psicologia expediente privado","psicologo dice a profesores","psicologo informa a familia","consulta psicologica privada","psicologia es segura","confidencialidad apoyo emocional","psicologo comparte informacion","psicologia confidencial","privacidad terapia uttt","psicologo secreto profesional","consulta emocional privada"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');

-- ID 279
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Dónde se encuentra el área de Psicología?','El área de Psicología se encuentra al interior de la Biblioteca de la Universidad en el campus Tula-Tepeji, en un horario de atención de lunes a viernes de 08:00 a 19:00 horas. La Biblioteca está ubicada en la zona central del campus. Puedes consultar el croquis en el siguiente enlace: https://www.uttt.edu.mx/Micrositio/croquis/. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["donde esta psicologia","ubicacion psicologia uttt","psicologia donde queda","area psicologia universidad","donde esta psicologo uttt","ubicacion apoyo psicologico","psicologia biblioteca uttt","como llegar psicologia","psicologo campus donde","ubicacion servicio psicologico","donde encontrar psicologia","psicologia horario y ubicacion","psicologia direccion uttt","psicologo en biblioteca","area emocional donde esta","ubicacion psicologia campus","psicologia lugar uttt","donde esta apoyo emocional","psicologia estudiantes ubicacion","ubicacion psicologo universidad"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil'); 

-- ID 280
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuántas sesiones puedo tener en el área de Psicología?','El proceso suele ser de terapia breve y enfocada, generalmente entre 6 y 8 sesiones. Si al finalizar requieres un acompañamiento más prolongado, se te brindará orientación y canalización externa para continuar con tu proceso. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["cuantas sesiones psicologia","cuantas terapias puedo tener","numero de sesiones psicologia","cuantas consultas psicologicas","cuanto dura tratamiento psicologico","cuantas citas psicologia uttt","numero sesiones terapia","cuantas veces puedo ir psicologia","limite sesiones psicologia","cuantas consultas puedo tener","sesiones psicologicas cuantas","cuanto dura proceso psicologico","cuantas citas puedo agendar","numero de terapias psicologia","cuantas sesiones maximo","cuantas veces psicologo uttt","cuanto dura apoyo psicologico","cuantas consultas emocionales","cuantas sesiones terapia uttt","limite terapia psicologica"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');  


-- ID 281
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué temas puedo tratar en el área de Psicología?','Se pueden atender diversos temas como ansiedad por exámenes, estrés, problemas de pareja, duelo, bajo rendimiento académico, entre otros. No hay problema pequeño; si algo te afecta, es importante y puedes recibir apoyo. Si tienes alguna duda, puedes comunicarte al correo desarrollo.estudiantil@uttt.edu.mx o al teléfono 773 732 9100 ext. 105.','alumnos',true,'["que atiende psicologia","temas psicologia universidad","problemas psicologicos que atienden","psicologia que ayuda","en que me puede ayudar psicologia","apoyo emocional temas","psicologia ayuda ansiedad","psicologia ayuda estres","problemas que atiende psicologo","psicologia estudiantes problemas","puedo ir por ansiedad psicologia","psicologia problemas personales","psicologo universidad que trata","temas terapia universidad","psicologia ayuda duelo","psicologia apoyo academico","problemas emocionales universidad","psicologia orientacion","en que me ayuda psicologo","psicologia apoyo emocional"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil'); 

-- ID 282
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Tengo una crisis y necesito atención psicológica','Si estás en una situación de peligro inmediato o crisis severa, por favor no esperes. Acude directamente al área de Psicología o al Servicio Médico de la universidad para recibir atención inmediata. También puedes comunicarte a la Línea de la Vida al 800 911 2000 o enviar un mensaje de WhatsApp a Contacto Joven al 55 7211 2009. Recuerda que no estás solo(a), pedir ayuda es un paso importante. Para apoyo institucional, puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167.','alumnos',true,'["tengo crisis ayuda","me siento mal urgente","necesito ayuda emocional urgente","crisis emocional que hago","me siento muy mal ayuda","ansiedad fuerte que hago","ataque de panico ayuda","necesito ayuda psicologica urgente","me siento en peligro emocional","crisis psicologica universidad","urgente apoyo emocional","no me siento bien ayuda","emergencia emocional que hago","me siento desesperado ayuda","crisis ansiedad que hago","necesito hablar urgente","me siento muy mal universidad","ayuda psicologica inmediata","crisis mental urgente","necesito ayuda ya"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil'); 


-- ID 283
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Me siento mal o necesito atención médica urgente','Si te sientes mal o presentas una situación de emergencia, mantén la calma y solicita apoyo a una persona cercana (compañero, docente o personal administrativo). Si puedes, acude de inmediato al Servicio Médico ubicado en el edificio UD3. En caso de no poder trasladarte, permanece en tu lugar y pide ayuda para que te asistan. Si es necesario, se activarán los protocolos de atención y traslado médico. También puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167 para recibir orientación.','alumnos',true,'["me siento mal","me siento muy mal","me siento mal que hago","necesito medico","necesito doctor","me siento mal en la escuela","emergencia medica","necesito ambulancia","me duele mucho","me duele mucho que hago","me siento muy mal ayuda","me desmaye","me desmaye que hago","me siento enfermo","necesito atencion medica urgente","me duele algo fuerte","me siento mal en campus","necesito ayuda medica","emergencia salud","me siento mal urgente","me paso algo necesito medico","me siento mal quien me ayuda","urgente medico universidad","me duele el pecho","no puedo respirar bien","me falta el aire","me mareo mucho","me estoy desmayando","me siento debil","me siento mal fisicamente","me lastime","tuve un accidente","me caí","me golpee fuerte","me siento grave","necesito ayuda urgente","me siento fatal","me siento muy debil","me siento inestable","necesito atencion inmediata","me duele demasiado","me siento mal y estoy solo","alguien ayudeme","me siento mal por favor ayuda","urgente ayuda medica","me siento mal y no puedo caminar","me siento mal y no puedo moverme"]'::jsonb,'Adriana Morales Montufar','Jefa de departamento','Departamento de Servicio Medico');

-- ID 284
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué hago si un amigo o amiga no se siente bien?','Lo mejor es acompañarlo y brindarle apoyo. Si se trata de una situación emocional o personal, puedes sugerirle que acuda al área de Psicología ubicada en la Biblioteca de la universidad, en un horario de lunes a viernes de 08:00 a 19:00 horas. Si la situación es física o de emergencia, apóyalo para acudir de inmediato al Servicio Médico en el edificio UD3. En caso necesario, no lo dejes solo y solicita ayuda a un docente o personal administrativo. También puedes comunicarte al correo medico@uttt.edu.mx o al teléfono 773 732 9100 ext. 167 para recibir orientación.','alumnos',true,'["mi amigo esta mal","amigo se siente mal","que hago si mi amigo esta mal","mi amigo necesita ayuda","amigo mal emocional","amigo en crisis","amigo necesita apoyo","amigo se siente mal que hago","mi amigo esta triste","mi amigo tiene ansiedad","amigo con problemas emocionales","amigo se siente mal fisicamente","mi amigo esta enfermo","amigo necesita ayuda urgente","que hacer por un amigo","como ayudar a un amigo mal","mi amigo no esta bien","amigo en problemas","amigo necesita medico","amigo necesita psicologo"]'::jsonb,'Ana Karen Vázquez Hernández','Jefe de departamento','Subdirección de Apoyo al Desarrollo Integral Estudiantil');


-- ID 285
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Dónde se encuentra el área de becas?','El área de becas se encuentra al interior de la Biblioteca de la Universidad, en el Departamento de Servicios Estudiantiles. El horario de atención es de lunes a viernes de 09:00 a 17:00 horas.','alumnos',true,'["donde esta becas","ubicacion becas uttt","donde queda becas","area de becas universidad","servicios estudiantiles donde esta","becas ubicacion uttt","donde encuentro becas","ubicacion servicios estudiantiles","becas en biblioteca uttt","como llegar a becas","donde esta apoyo becas","area becas campus","ubicacion becas universidad","servicios estudiantiles ubicacion","donde esta departamento becas","becas donde acudir","oficina becas uttt","donde preguntar por becas","ubicacion becas estudiantes","donde esta servicios estudiantiles"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 286
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuándo hay convocatorias de becas del gobierno?','Las convocatorias de becas del gobierno suelen publicarse en dos periodos del año: entre febrero y marzo, y entre septiembre y octubre. Sin embargo, es importante mantenerse al pendiente durante todo el año, ya que pueden abrirse convocatorias en otros meses.','alumnos',true,'["cuando salen becas gobierno","fechas becas gobierno","convocatorias becas cuando","cuando abren becas gobierno","becas gobierno fechas","cuando hay becas externas","convocatoria becas gobierno mexico","cuando puedo aplicar a becas","becas cuando salen","fechas convocatorias becas","cuando abren becas estudiantes","convocatoria becas fechas","cuando salen apoyos gobierno","becas externas cuando salen","periodos becas gobierno","cuando aplicar becas","becas fechas mexico","convocatorias gobierno estudiantes","cuando hay apoyos economicos","fechas becas estudiantes"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 287
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué tipos de becas ofrece la universidad?','La universidad cuenta con distintos tipos de becas. Existen becas académicas y de excelencia, donde participan los estudiantes con mejores promedios (de 9.0 a 9.5 para académicas y de 9.5 a 10 para excelencia). También se ofrecen becas alimenticias mediante convocatoria al inicio de cada cuatrimestre, las cuales consisten en una comida diaria de lunes a viernes. Además, hay becas para hijos de padres militares en activo, jubilados o fallecidos. Para mayor información sobre requisitos y procesos, se recomienda acudir al Departamento de Servicios Estudiantiles.','alumnos',true,'["que becas hay en la universidad","tipos de becas uttt","becas disponibles uttt","becas que ofrece la universidad","becas academicas uttt","beca excelencia uttt","becas alimenticias uttt","becas militares uttt","que apoyos hay uttt","becas universidad cuales son","tipos de apoyos economicos uttt","becas estudiantes uttt","beneficios becas uttt","becas internas universidad","que becas puedo solicitar","becas disponibles estudiantes","programas de becas uttt","becas alimentacion universidad","becas por promedio uttt","becas servicios estudiantiles"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 288
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo obtener una beca si soy menor de edad?','Para las becas institucionales que otorga la Universidad no existe problema si eres menor de edad. En el caso de becas externas (de gobierno, instituciones o dependencias), es importante revisar las convocatorias, ya que algunas pueden requerir documentos como el INE.','alumnos',true,'["menor de edad beca","puedo tener beca siendo menor","becas para menores de edad","necesito ser mayor para beca","becas si soy menor","puedo aplicar beca sin ine","becas requisitos edad","edad para becas universidad","menor puede tener beca uttt","becas estudiantes menores","puedo sacar beca sin ser mayor","becas sin ine posible","edad minima para becas","becas gobierno edad requisito","becas institucionales menor edad","puedo tener beca con 17 años","becas universidad edad","menor aplica becas","becas requisitos edad uttt","puedo tener beca siendo estudiante menor"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 289
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Puedo tener más de una beca al mismo tiempo?','En el caso de becas externas (de gobierno, instituciones u otras dependencias), generalmente no es posible contar con más de una, por lo que es importante revisar las convocatorias, donde se indica la compatibilidad. Sin embargo, sí es posible tener una beca institucional de la Universidad y una beca externa al mismo tiempo.','alumnos',true,'["puedo tener dos becas","tener varias becas uttt","puedo tener mas de una beca","becas compatibles","puedo combinar becas","dos becas al mismo tiempo","puedo tener beca gobierno y universidad","compatibilidad becas","puedo tener varias becas estudiantes","becas juntas se puede","puedo recibir dos apoyos","becas externas e internas juntas","puedo tener dos apoyos economicos","becas simultaneas estudiantes","puedo tener varias ayudas","compatibilidad becas universidad","dos becas al mismo tiempo posible","puedo tener beca doble","becas combinadas estudiantes","puedo tener becas multiples"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 290
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué beneficios obtengo al tener una beca?','Los beneficios dependen del tipo de beca. Algunas son económicas, donde recibes un apoyo monetario conforme a la convocatoria. Otras son en especie, como las becas alimenticias que incluyen una comida diaria. También existen becas que ofrecen cursos o descuentos en el pago de reinscripción, como las académicas, de excelencia o para hijos de padres militares.','alumnos',true,'["que dan las becas","beneficios becas uttt","que incluye una beca","que obtengo con beca","becas que ofrecen beneficios","que me dan si tengo beca","apoyos becas universidad","beneficios economicos becas","becas alimenticias que dan","becas descuento reinscripcion","becas que cubren","que incluye beca universidad","beneficios estudiante beca","becas apoyo monetario","becas que ofrecen comida","beneficios becas estudiantes","que cubre una beca","becas universidad beneficios","apoyo beca que incluye","beneficios beca uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 291
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Si ya tengo una beca, ¿cuándo recibo el pago?','Las fechas de depósito de las becas económicas dependen de los procesos administrativos necesarios para la generación de cuentas bancarias. Por ello, se recomienda acudir al área de becas después de la publicación de resultados para recibir información actualizada sobre tu pago.','alumnos',true,'["cuando pagan la beca","fecha pago beca","cuando depositan beca","cuando cae la beca","beca cuando depositan","pago beca estudiantes","cuando recibo mi beca","fecha deposito beca","cuando llega el dinero beca","beca pago cuando","cuando dan beca","cuando se paga beca universidad","pago apoyo economico cuando","cuando depositan apoyo","beca cuando llega","cuando me pagan beca","fecha pago estudiantes beca","cuando cae apoyo economico","beca cuando dan dinero","cuando depositan beca uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 292
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Si ya tengo una beca, ¿debo renovarla para seguir recibiéndola?','No, las becas no se renuevan automáticamente. Es necesario participar nuevamente en cada convocatoria, ya que cada una establece su propio periodo de vigencia y requisitos.','alumnos',true,'["renovar beca","tengo que renovar beca","beca se renueva sola","como renovar beca uttt","beca continuidad","debo volver a aplicar beca","beca sigue automaticamente","renovacion beca estudiantes","beca tengo que hacer tramite otra vez","beca cada cuanto se renueva","beca vigencia cuanto dura","beca tengo que aplicar de nuevo","renovacion apoyo economico","beca se vuelve a solicitar","continuidad beca universidad","beca se mantiene sola","tengo que hacer tramite beca otra vez","beca aplica cada convocatoria","beca proceso renovacion","beca tengo que volver a registrarme"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 293
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Si soy de otro estado, ¿puedo obtener una beca?','Sí, puedes obtener una beca. En el caso de becas externas, es importante revisar las convocatorias, ya que pueden solicitar requisitos adicionales como constancia de radicación. Para las becas que otorga la Universidad, no es necesario demostrar radicación.','alumnos',true,'["soy de otro estado beca","puedo tener beca si no soy de hidalgo","becas estudiantes foraneos","becas otro estado universidad","soy foraneo puedo tener beca","becas fuera de hidalgo","beca si soy de otro estado","puedo aplicar beca siendo foraneo","becas estudiantes de otros estados","beca universidad foraneo","becas requisitos residencia","becas con residencia necesaria","puedo tener beca sin ser local","becas para foraneos uttt","becas externos requisitos","puedo tener beca si no soy de aqui","becas estudiantes fuera estado","becas sin radicar hidalgo","becas para foraneos universidad","becas requisitos estado"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 294
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué documentos necesito para solicitar una beca?','Los documentos pueden variar dependiendo de la convocatoria. Sin embargo, generalmente se solicita contar con CURP actualizada y una identificación oficial como el INE. Se recomienda revisar cuidadosamente los requisitos específicos de cada convocatoria.','alumnos',true,'["documentos beca","que necesito para beca","requisitos beca uttt","papeles para beca","documentos necesarios beca","requisitos becas estudiantes","que piden para beca","beca requisitos documentos","papeles beca universidad","que llevar para beca","requisitos apoyo economico","documentos becas gobierno","requisitos becas externas","papeles necesarios beca","que documentos piden beca","requisitos convocatoria beca","documentos beca estudiantes","que necesito para apoyo economico","requisitos beca universidad","papeles beca uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 295
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Necesito una cuenta bancaria para recibir mi beca?','No es necesario contar con una cuenta bancaria, ya que las Coordinaciones de Becas se encargan de generar las cuentas para que puedas recibir el apoyo económico.','alumnos',true,'["necesito cuenta para beca","cuenta bancaria beca","tengo que tener banco beca","beca deposito banco","cuenta para recibir beca","necesito tarjeta para beca","beca requiere cuenta bancaria","como recibo beca dinero","beca donde depositan","necesito banco para beca","beca sin cuenta bancaria","me depositan beca donde","cuenta bancaria obligatoria beca","beca sin tarjeta posible","como me pagan beca","beca deposito como funciona","cuenta banco necesaria beca","beca donde llega dinero","necesito abrir cuenta beca","beca pago banco"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 296
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Con qué color de pluma debo firmar los documentos para la beca?','Se recomienda firmar los documentos con tinta de color azul.','alumnos',true,'["color pluma beca","con que pluma firmo beca","color tinta beca","pluma azul beca","puedo firmar negro beca","color firma documentos beca","como firmar documentos beca","pluma para firmar beca","color tinta firma beca","firma documentos color","beca firma azul","color pluma documentos","tinta recomendada beca","firmar beca color","pluma azul obligatorio beca","color firma universidad","documentos beca tinta","pluma recomendada beca","firma autografa color","color para firmar beca"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 297
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿A qué se refiere la firma autógrafa en los documentos de beca?','Se refiere a que debes realizar tu firma de manera manual, con tu puño y letra, utilizando lapicero (preferentemente de tinta azul).','alumnos',true,'["firma autografa que es","que significa firma autografa","firma manual beca","como firmar documentos beca","firma con pluma que es","firma autografa ejemplo","firma documentos a mano","que es firma autografa beca","firma original documentos","firma con puño y letra","como hacer firma autografa","firma manual requisitos","firma documentos universidad","firma autografa significado","firma con tinta beca","firma original que es","como firmar beca","firma documentos estudiantes","firma a mano que es","firma autografa universidad"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 298
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué requisitos debo cumplir para tramitar una baja temporal o definitiva?','Para tramitar una baja es necesario cumplir con los siguientes requisitos: 1) Presentar tu credencial institucional vigente; en caso de extravío, deberás presentar una copia de tu INE. 2) Notificar previamente a tu familiar o tutor legal registrado en la institución sobre tu decisión. 3) No contar con adeudos de material en biblioteca, laboratorios o pagos pendientes.','alumnos',true,'["requisitos baja universidad","que necesito para darme de baja","requisitos baja temporal","requisitos baja definitiva","que piden para baja","documentos para baja universidad","que necesito para baja uttt","requisitos para darme de baja","que debo tener para baja","baja requisitos estudiantes","tramite baja requisitos","que necesito para baja escolar","requisitos baja alumnos","documentos baja universidad","que piden para baja uttt","requisitos para salir de la universidad","que necesito para tramitar baja","baja requisitos control escolar","requisitos baja temporal uttt","requisitos baja definitiva uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 299
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué pasos debo seguir para tramitar una baja temporal o definitiva?','Para formalizar tu baja debes seguir estos pasos: 1) Acudir con tu Tutor(a) de Acompañamiento para recibir orientación sobre las implicaciones y opciones disponibles. 2) Presentarte en el área de Psicología para una entrevista, con el fin de conocer los motivos y brindarte apoyo si es necesario. 3) Finalmente, acudir al Departamento de Control Escolar para entregar los formatos correspondientes y, en su caso, recibir tus documentos originales según el tipo de baja.','alumnos',true,'["pasos para baja universidad","como darme de baja pasos","proceso baja uttt","como tramitar baja","pasos baja temporal","pasos baja definitiva","como hacer baja universidad","tramite baja pasos","que hacer para darme de baja","proceso para baja escolar","pasos control escolar baja","como iniciar baja universidad","pasos baja alumnos","como hacer tramite baja","baja proceso completo","pasos para salir de la universidad","como tramitar baja escolar","baja universidad pasos","proceso baja estudiantes","como darme de baja uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 300
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿En dónde puedo tramitar mi baja?','El trámite de baja se inicia en el Edificio de Biblioteca "Dr. Miguel León Portilla", específicamente en la oficina de Servicios Estudiantiles, dentro del área de Psicología. La Biblioteca se encuentra en la zona central del campus. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["donde tramitar baja","donde hago mi baja","ubicacion baja universidad","donde ir para baja uttt","oficina baja universidad","donde se hace la baja","donde acudir para baja","area baja estudiantes","ubicacion servicios estudiantiles baja","donde iniciar tramite baja","donde queda control baja","oficina servicios estudiantiles baja","donde hago baja temporal","donde hago baja definitiva","donde iniciar baja universidad","lugar para baja uttt","donde entrego documentos baja","donde pedir baja universidad","ubicacion psicologia baja","donde esta oficina de baja"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 301
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Existe una fecha límite para solicitar la baja sin afectar mi historial?','Puedes solicitar tu baja (temporal o definitiva) en cualquier momento del cuatrimestre. No existe una fecha límite restrictiva; sin embargo, se recomienda realizar el trámite antes de finalizar el periodo de evaluaciones para mantener un historial administrativo limpio. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["fecha limite baja","hasta cuando puedo darme de baja","baja afecta historial cuando","puedo darme de baja en cualquier momento","fecha para baja universidad","cuando darme de baja uttt","baja sin afectar historial","cuando es tarde para baja","fecha maxima baja","puedo darme de baja despues examenes","baja en cualquier momento posible","cuando solicitar baja","limite baja estudiantes","cuando puedo tramitar baja","baja antes de evaluaciones","fecha corte baja universidad","baja afecta calificaciones","cuando hacer baja uttt","fecha limite baja escolar","puedo hacer baja cualquier fecha"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 302
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuál es la vigencia de una baja temporal o definitiva?','Tanto la baja temporal como la definitiva tienen una vigencia de 1 año. Durante este periodo puedes reincorporarte de manera oficial conservando tu estatus previo. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["vigencia baja","cuanto dura la baja","tiempo baja universidad","vigencia baja temporal","vigencia baja definitiva","cuanto tiempo puedo regresar despues de baja","baja cuanto dura","tiempo para regresar universidad","cuanto dura baja uttt","vigencia baja estudiantes","baja tiempo limite","cuanto tiempo tengo para volver","baja periodo vigencia","tiempo de baja universidad","baja cuanto tiempo aplica","vigencia baja escolar","cuanto dura baja temporal uttt","cuanto dura baja definitiva uttt","tiempo para reincorporarse","baja universidad vigencia"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 303
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Si me doy de baja definitiva, ¿puedo regresar a la universidad?','Sí, puedes regresar. Sin embargo, si ha pasado más de un año desde que realizaste tu baja, deberás realizar nuevamente el proceso de inscripción completo, tal como cuando ingresaste por primera vez. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["baja definitiva puedo regresar","puedo volver despues de baja","regresar universidad despues de baja","baja definitiva regreso","puedo reinscribirme despues de baja","volver a estudiar despues de baja","baja definitiva uttt regresar","puedo volver a entrar universidad","regreso despues de baja cuanto tiempo","puedo regresar despues de darme de baja","baja definitiva y reinscripcion","volver universidad requisitos baja","puedo regresar escuela despues de baja","baja definitiva volver a estudiar","regreso universidad baja definitiva","puedo entrar de nuevo universidad","baja definitiva proceso regreso","volver a inscribirme despues de baja","puedo regresar si me di de baja","baja definitiva cuanto tiempo regresar"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 304
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Si me doy de baja, ¿qué pasa con mis documentos originales?','Los documentos originales se entregan únicamente en el Departamento de Control Escolar al momento de tramitar una baja definitiva. En el caso de una baja temporal, los documentos permanecen bajo resguardo de la Universidad para facilitar tu reingreso. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["documentos originales baja","me regresan documentos baja","documentos al darme de baja","documentos universidad baja","que pasa con mis papeles baja","documentos control escolar baja","me dan mis documentos originales","documentos baja temporal","documentos baja definitiva","papeles universidad baja","me entregan documentos baja","documentos al salir universidad","papeles originales baja","donde recojo documentos baja","control escolar documentos baja","documentos regreso baja","papeles al darme de baja","documentos universidad que pasa","documentos al hacer baja","papeles originales universidad baja"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 305
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Dónde puedo consultar mis horas taller acumuladas?','Puedes verificar tu acumulado y el registro de tus actividades directamente en el S.I.G.E. (Sistema Integral de Gestión Educativa), dentro del apartado "Consultor de Horas Taller". Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["horas taller donde ver","consultar horas taller","ver horas taller sige","donde ver horas acumuladas","horas taller uttt consulta","como ver horas taller","sige horas taller","donde consultar actividades taller","horas taller estudiantes","ver acumulado horas taller","consultar horas sige","donde revisar horas taller","horas taller registro","sistema horas taller uttt","consultor horas taller","donde veo mis horas taller","horas taller plataforma","ver horas actividades uttt","consultar horas acumuladas sige","donde ver progreso horas taller"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 306
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo puedo inscribirme a las actividades que liberan horas taller?','Puedes inscribirte a las actividades de horas taller de dos formas: 1) Consultando la oferta directamente con tu Dirección de Carrera. 2) Acudiendo a la Subdirección de Apoyo al Desarrollo Integral Estudiantil, ubicada en el Edificio de Biblioteca, donde podrás conocer la programación completa del cuatrimestre. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["como inscribirme horas taller","inscripcion actividades horas taller","como liberar horas taller","donde inscribirme horas taller","actividades horas taller como entrar","registro horas taller uttt","como participar actividades taller","horas taller inscripcion","como entrar a talleres uttt","inscripcion actividades universidad","horas taller actividades como hacer","como obtener horas taller","donde ver actividades horas taller","como anotarme en talleres","registro actividades estudiantes","inscripcion talleres universidad","como acceder a horas taller","actividades estudiantiles horas taller","como hacer horas taller","registro horas taller estudiantes"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 307
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuántas horas taller se acreditan por cada actividad o conferencia?','El número de horas que se otorgan por actividad o conferencia puede variar, generalmente desde 5 hasta 40 horas, dependiendo del tipo de evento y su duración. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["cuantas horas da cada actividad","horas taller por evento","cuantas horas dan talleres","horas por conferencia uttt","valor horas taller actividad","cuantas horas dan cursos","horas taller equivalencia","cuantas horas vale cada actividad","horas por evento universidad","cuantas horas acredita actividad","horas taller cuanto dan","valor horas actividades uttt","cuantas horas suman talleres","horas taller por conferencia","cuantas horas dan eventos","horas taller cuantos puntos","valor actividades horas taller","horas por cursos uttt","cuantas horas se obtienen actividad","horas taller valor evento"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');   


-- ID 308
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cuántas horas taller debo acumular?','Debes acumular un total de 240 horas taller. Se recomienda planificar y distribuir tus actividades con anticipación, ya que es un requisito indispensable para poder realizar tu estadía. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["cuantas horas taller necesito","horas taller requeridas","cuantas horas debo tener uttt","requisito horas taller","cuantas horas para estadia","horas taller necesarias estudiantes","cuantas horas debo cumplir","total horas taller","cuantas horas piden universidad","horas taller requisito estadia","cuantas horas acumuladas necesito","requisito horas taller uttt","horas taller obligatorias","cuantas horas necesito para estadia","total horas actividades uttt","horas taller meta","cuantas horas debo completar","horas taller cuanto es","requisito horas taller estudiantes","horas taller minimo"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles'); 

-- ID 309
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Existe un límite de horas taller que puedo acumular por cuatrimestre?','No existe un límite de horas taller por cuatrimestre; puedes acumular tantas como desees. Sin embargo, es obligatorio completar un total de 240 horas antes de iniciar tu estadía (5° cuatrimestre). Se recomienda llevar un seguimiento constante para cumplir con este requisito en tiempo. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["limite horas taller","cuantas horas maximas taller","horas taller limite","puedo hacer muchas horas taller","maximo horas taller por cuatrimestre","limite actividades horas taller","cuantas horas puedo acumular","tope horas taller","horas taller sin limite","cuantas horas por periodo taller","maximo horas actividades uttt","horas taller restricciones","puedo acumular muchas horas","horas taller cuantas por cuatrimestre","hay limite horas taller","horas taller cuantos puedo hacer","tope actividades estudiantes","horas taller maximo permitido","cuantas horas puedo hacer por periodo","limite horas taller universidad"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 310
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Qué validez tienen las horas taller para mi estadía o titulación?','La liberación de las 240 horas taller es un requisito indispensable para ser autorizado a realizar la estadía técnica. Una vez completadas, puedes descargar tu comprobante de conclusión directamente desde el S.I.G.E. (Sistema Integral de Gestión Educativa). Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["horas taller para estadia","validez horas taller","horas taller requisito estadia","para que sirven horas taller","horas taller titulación","horas taller obligatorias estadia","requisito estadia horas taller","horas taller comprobante","horas taller sige descargar","para que sirven horas taller uttt","horas taller importancia","horas taller requisito universidad","comprobante horas taller","horas taller necesarias estadia","validacion horas taller","horas taller proceso estadia","horas taller requisito titulación","horas taller para graduarse","descargar horas taller sige","horas taller comprobante uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 311
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿En dónde puedo ver mis horas taller?','Puedes consultar tus horas taller directamente en tu portal estudiantil S.I.G.E., donde se reflejan en la pantalla principal. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["donde ver horas taller rapido","ver horas taller portal","horas taller sige pantalla principal","donde aparecen horas taller","ver horas taller inicio sige","portal horas taller","horas taller donde salen","consultar horas taller rapido","ver horas taller sistema","horas taller en portal estudiante","donde se reflejan horas taller","horas taller pantalla principal sige","como ver horas taller rapido","horas taller donde ver en sige","ver horas taller inicio portal","horas taller portal estudiantil","donde ver mis horas sige","horas taller visibles donde","portal estudiante horas taller","ver horas taller directo"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');



-- ID 312
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Quiero cambiarme de otra universidad a la UTTT, ¿qué debo hacer?','Si deseas cambiarte de otra universidad a la UTTT, es necesario realizar un proceso de equivalencia de estudios. Para iniciar este trámite deberás presentar: solicitud de equivalencia, copia de identificación oficial, copia del certificado de bachillerato, original y copia del certificado de estudios de tu institución de procedencia (no se acepta historial académico ni constancia de estudios), así como los contenidos programáticos de las materias cursadas en formato digital. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','aspirantes',true,'["quiero cambiarme de universidad","como cambiarme a uttt","transferirme a uttt","cambio de universidad requisitos","equivalencia estudios uttt","revalidacion materias uttt","como entrar a uttt desde otra escuela","quiero estudiar en uttt vengo de otra universidad","cambio de institucion como hacer","transferencia universidad uttt","revalidacion estudios uttt","equivalencia materias universidad","cambio universidad procedimiento","transferirme de escuela","como cambiar de universidad","equivalencia documentos requisitos","cambio universidad que necesito","quiero cambiar de escuela a uttt","revalidar materias uttt","equivalencia de estudios como hacer"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 313
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('Soy egresado de TSU, ¿puedo continuar mis estudios en la UTTT?','Sí, puedes continuar tus estudios en la UTTT. Para iniciar el proceso deberás presentar historial académico, copia de identificación oficial, original y copia del certificado parcial de la universidad de procedencia, así como una carta de buena conducta emitida por dicha institución. Una vez que cuentes con esta documentación, se te orientará sobre los siguientes pasos para tu inscripción. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','aspirantes',true,'["soy tsu puedo seguir estudiando","continuar estudios tsu","seguir licenciatura despues de tsu","puedo estudiar licenciatura tsu","tsu continuar estudios uttt","egresado tsu puedo seguir estudiando","continuar estudios universidad tecnologica","tsu a licenciatura uttt","seguir estudiando despues de tsu","requisitos continuar estudios tsu","puedo seguir licenciatura uttt","egresado tsu requisitos","continuar carrera tsu","tsu a ingenieria uttt","seguir estudios superiores tsu","tsu licenciatura requisitos","puedo entrar licenciatura tsu","continuar estudios universidad tecnologica uttt","tsu continuar ingenieria","egresado tsu seguir estudios"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  


-- ID 314
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo solicito una constancia de estudios?','Para solicitar tu constancia de estudios, primero debes realizar el pago correspondiente. Puedes hacerlo en practicaja o cajero BBVA siguiendo estos pasos: 1) Selecciona "Pagar". 2) Ingresa a "Servicios". 3) Elige forma de pago (efectivo o tarjeta). 4) Ingresa el número de convenio: 1505106. 5) Captura la referencia que aparece en tu ficha de pago. 6) Ingresa el monto a pagar. 7) Confirma la operación. 8) Realiza el pago y conserva tu comprobante. Posteriormente, presenta tu comprobante de pago en el Departamento de Control Escolar para iniciar el trámite. La constancia se entrega al momento. Si necesitas solicitar el formato de pago, puedes hacerlo al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["constancia de estudios","como sacar constancia","tramitar constancia estudios","constancia uttt como sacar","quiero constancia de estudios","solicitar constancia universidad","constancia escolar como obtener","constancia alumnos uttt","constancia inmediata universidad","como pedir constancia","constancia control escolar","constancia requisitos uttt","constancia donde sacar","constancia tiempo entrega","constancia escolar uttt","tramite constancia estudiantes","como obtener constancia universidad","constancia en control escolar","constancia proceso uttt","solicitud constancia estudios"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');


-- ID 315
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo solicito una constancia de autenticidad de mi título de licenciatura?','Para solicitar la constancia de autenticidad de tu título de licenciatura, es necesario enviar la siguiente información: nombre completo, nombre de la carrera, matrícula y tu título en formato PDF. Una vez que se cuente con estos datos, el área correspondiente te proporcionará los requisitos, costos y tiempos de entrega para el trámite. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["constancia autenticidad titulo","validar titulo licenciatura","constancia autenticidad universidad","mi titulo tiene firma electronica","validacion titulo uttt","constancia para trabajo titulo","verificar autenticidad titulo","constancia titulo universidad","como validar mi titulo","documento autenticidad titulo","constancia titulo empleo","validar titulo profesional uttt","constancia firma autografa titulo","mi titulo no tiene firma autografa","constancia autenticidad requisitos","validacion titulo licenciatura uttt","constancia oficial titulo","comprobar autenticidad titulo","tramite autenticidad titulo","validar titulo para trabajo"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 316
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo solicito mi constancia de estudios?','Para solicitar tu constancia de estudios, deberás realizar el pago correspondiente en caja y posteriormente presentar tu comprobante de pago en el Departamento de Control Escolar para iniciar el trámite. La solicitud de concepto de pago puede solicitarse al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["constancia de estudios","como sacar constancia","tramitar constancia estudios","constancia uttt como sacar","quiero constancia de estudios","solicitar constancia universidad","constancia escolar como obtener","constancia alumnos uttt","constancia inmediata universidad","como pedir constancia","constancia control escolar","constancia requisitos uttt","constancia donde sacar","constancia tiempo entrega","constancia escolar uttt","tramite constancia estudiantes","como obtener constancia universidad","constancia en control escolar","constancia proceso uttt","solicitud constancia estudios"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');



-- ID 317
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo tramito mi historial académico (kardex)?','Para tramitar tu historial académico (kardex), deberás realizar el pago correspondiente en caja y posteriormente presentar tu comprobante de pago en el Departamento de Control Escolar para dar inicio al trámite. La solicitud de concepto de pago puede solicitarse al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["kardex uttt","historial academico","como sacar kardex","tramitar kardex","historial academico como obtener","kardex estudiantes uttt","solicitar historial academico","kardex control escolar","como pedir kardex","historial calificaciones completo","kardex universidad","tramite kardex estudiantes","historial academico requisitos","kardex donde sacar","kardex proceso uttt","como obtener historial academico","kardex calificaciones","historial escolar uttt","solicitud kardex","historial academico completo"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 318
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo solicito mi boleta de calificaciones?','Para solicitar tu boleta de calificaciones, deberás realizar el pago correspondiente en caja y posteriormente presentar o enviar vía correo electrónico tu comprobante de pago al Departamento de Control Escolar para dar inicio al trámite. La solicitud de concepto de pago puede solicitarse al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["boleta de calificaciones","como sacar boleta","tramitar boleta uttt","boleta universidad como obtener","calificaciones boleta uttt","solicitar boleta calificaciones","boleta control escolar","como pedir boleta","boleta estudiantes uttt","boleta escolar universidad","tramite boleta estudiantes","boleta requisitos uttt","boleta donde sacar","boleta proceso uttt","como obtener boleta universidad","boleta calificaciones completo","boleta sige no aparece","boleta escolar uttt","solicitud boleta calificaciones","boleta notas universidad"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 319
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo puedo solicitar un certificado parcial o total de estudios?','Para solicitar un certificado parcial o total de estudios, deberás realizar el pago correspondiente en caja y posteriormente presentar tu comprobante de pago en el Departamento de Control Escolar, con lo cual el trámite se genera de manera inmediata. La solicitud de concepto de pago puede solicitarse al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["certificado parcial estudios","certificado total estudios","como sacar certificado universidad","tramitar certificado estudios","certificado uttt como obtener","solicitar certificado parcial","solicitar certificado total","certificado control escolar","como pedir certificado estudios","certificado escolar universidad","tramite certificado estudiantes","certificado requisitos uttt","certificado donde sacar","certificado proceso uttt","como obtener certificado universidad","certificado estudios completo","certificado parcial requisitos","certificado total requisitos","solicitud certificado estudios","certificado escolar uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 319
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo puedo solicitar un certificado parcial o total de estudios?','Para solicitar un certificado parcial o total de estudios, deberás realizar el pago correspondiente en caja y posteriormente presentar tu comprobante de pago en el Departamento de Control Escolar, con lo cual el trámite se genera de manera inmediata. La solicitud de concepto de pago puede solicitarse al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["certificado parcial estudios","certificado total estudios","como sacar certificado universidad","tramitar certificado estudios","certificado uttt como obtener","solicitar certificado parcial","solicitar certificado total","certificado control escolar","como pedir certificado estudios","certificado escolar universidad","tramite certificado estudiantes","certificado requisitos uttt","certificado donde sacar","certificado proceso uttt","como obtener certificado universidad","certificado estudios completo","certificado parcial requisitos","certificado total requisitos","solicitud certificado estudios","certificado escolar uttt"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 320
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES ('¿Cómo puedo solicitar un duplicado de certificado?','Para solicitar un duplicado de certificado, deberás realizar el pago correspondiente en caja y posteriormente presentar tu comprobante de pago en el Departamento de Control Escolar para iniciar el trámite. El personal del área te indicará el tiempo estimado de entrega. La solicitud de concepto de pago puede solicitarse al correo caja@uttt.edu.mx. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','alumnos',true,'["duplicado certificado estudios","reponer certificado universidad","certificado perdido que hago","tramitar duplicado certificado","duplicado certificado uttt","como sacar copia certificado","certificado extraviado universidad","solicitar duplicado certificado","certificado reposicion","como recuperar certificado estudios","duplicado certificado requisitos","certificado control escolar duplicado","tramite duplicado certificado","certificado copia universidad","certificado perdido reposicion","duplicado certificado escolar","solicitud duplicado certificado","certificado extraviado que hacer","duplicado certificado proceso","certificado universidad copia"]'::jsonb,'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

-- ID 321
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cuándo son las fechas de inscripción o reinscripción?','Las fechas de inscripción o reinscripción se dan a conocer a través de los medios oficiales de la universidad, por lo que se recomienda estar al pendiente de su publicación. Para más información, puedes comunicarte al correo servicios.estudiantiles@uttt.edu.mx o al teléfono 773 732 9100 ext. 456.','aspirantes',true,
'["fechas inscripcion uttt","cuando inscripciones universidad","fechas reinscripcion uttt","cuando me puedo inscribir","inscripciones universidad fechas","convocatoria inscripcion uttt","cuando hay reinscripciones","fechas de ingreso universidad","cuando salen fechas uttt","inscripcion universidad cuando es"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 322
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Qué documentos necesito para inscribirme?','Para inscribirte al primer cuatrimestre necesitas presentar: certificado de bachillerato (original), acta de nacimiento (original), comprobante de domicilio (copia), CURP (copia) y formato de inscripción (original). Asegúrate de que todos los documentos estén completos y en buen estado para evitar contratiempos.','aspirantes',true,
'["documentos inscripcion uttt","requisitos inscripcion universidad","papeles para inscribirme","que necesito para inscribirme uttt","requisitos ingreso universidad","documentos universidad ingreso","papeles para universidad","inscripcion documentos necesarios","requisitos estudiantes nuevo ingreso","documentos primer ingreso uttt"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');
-- ID 323
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo solicito una baja temporal?','Para solicitar una baja temporal, deberás acudir a la Subdirección de Apoyo al Desarrollo Integral Estudiantil (Psicología) para la entrevista correspondiente. Posteriormente, se notificará al Departamento de Control Escolar para registrar el trámite.','alumnos',true,
'["baja temporal como hacer","tramitar baja temporal","como darme de baja temporal","baja temporal uttt","proceso baja temporal","solicitar baja temporal universidad","baja temporal estudiantes","como hacer baja temporal escuela","tramite baja temporal uttt","baja temporal requisitos"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

-- ID 324

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo puedo tramitar una baja definitiva?','Para tramitar una baja definitiva, deberás acudir a la Subdirección de Apoyo al Desarrollo Integral Estudiantil (Psicología) para la entrevista correspondiente. Posteriormente, se notificará al Departamento de Control Escolar para registrar el trámite correspondiente.','alumnos',true,
'["baja definitiva como hacer","tramitar baja definitiva","darme de baja definitiva","baja definitiva uttt","proceso baja definitiva","solicitar baja definitiva universidad","baja definitiva estudiantes","como salir de la universidad","tramite baja definitiva uttt","baja definitiva requisitos"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

--ID 325 
INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo tramito mi credencial institucional?','Para tramitar tu credencial institucional, deberás realizar el pago correspondiente en caja y presentar tu comprobante en el Departamento de Control Escolar, donde se generará y entregará tu credencial al momento. La solicitud de pago puede hacerse al correo caja@uttt.edu.mx.','alumnos',true,
'["credencial institucional uttt","tramitar credencial","como sacar credencial universidad","credencial estudiante uttt","reponer credencial","credencial control escolar","como obtener credencial","tramite credencial estudiantes","credencial universidad proceso","credencial estudiante como sacar"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

--ID 326

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo recupero mi contraseña del SIGE?','La recuperación de contraseña del SIGE se realiza de forma presencial en el Departamento de Servicios Escolares, donde se te brindará el apoyo correspondiente.','alumnos',true,
'["recuperar contraseña sige","olvide contraseña sige","cambiar contraseña sige","no puedo entrar sige","recuperar acceso sige","contraseña sige uttt","problemas sige acceso","como recuperar sige","acceso sige estudiantes","recuperar cuenta sige"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Qué requisitos necesito para titularme?','Debes cumplir con requisitos como no tener adeudos, entregar documentación requerida, realizar pagos de titulación, concluir tu estadía y cumplir con los procesos establecidos en tiempo según la convocatoria vigente.','alumnos',true,
'["requisitos titulacion","como titularme uttt","proceso titulacion","que necesito para titularme","titulacion universidad requisitos","tramite titulo requisitos","como obtener titulo universidad","requisitos titulo profesional","proceso titulacion uttt","titulacion estudiantes requisitos"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles'); 

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cuánto tarda la entrega del título?','El tiempo estimado para el trámite de registro del título es de 6 a 8 meses cuando se realiza con tu generación de egreso. En otros casos, puede tardar más tiempo.','alumnos',true,
'["cuanto tarda titulo","tiempo entrega titulo","cuanto tarda cedula titulo","titulo cuanto tarda","entrega titulo universidad tiempo","tiempo tramite titulo","titulo profesional tiempo","cuanto tarda titulacion","tiempo titulo uttt","titulo cuanto tarda meses"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo puedo obtener mi cédula profesional?','Una vez concluido el registro de tu título, el Departamento de Control Escolar te notificará para iniciar el trámite de tu cédula profesional, el cual se realiza directamente ante la Dirección General de Profesiones.','alumnos',true,
'["cedula profesional como sacar","tramitar cedula profesional","cedula despues titulo","como obtener cedula","cedula profesional mexico tramite","cedula proceso uttt","como sacar cedula profesional","tramite cedula estudiantes","cedula requisitos","cedula profesional proceso"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo puedo solicitar un cambio de carrera?','Para solicitar un cambio de carrera, deberás acudir con el Director de tu Programa Educativo, quien te indicará el procedimiento a seguir.','alumnos',true,
'["cambio de carrera uttt","como cambiar carrera","tramitar cambio carrera","cambiar de carrera universidad","cambio carrera proceso","como cambiar de carrera uttt","cambio carrera requisitos","tramite cambio carrera","cambiar carrera estudiantes","cambio carrera universidad"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Qué hago si hay un error en mi calificación?','Debes reportarlo con el Director de tu Programa Educativo para que se realice la revisión correspondiente y, en su caso, se haga la corrección.','alumnos',true,
'["error calificacion","calificacion incorrecta","nota mal puesta","error en calificaciones","corregir calificacion","calificacion mal sistema","error sige calificacion","calificacion incorrecta uttt","revisar calificacion","correccion calificacion"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Qué hago si hay un error en mi calificación?','Debes reportarlo con el Director de tu Programa Educativo para que se realice la revisión correspondiente y, en su caso, se haga la corrección.','alumnos',true,
'["error calificacion","calificacion incorrecta","nota mal puesta","error en calificaciones","corregir calificacion","calificacion mal sistema","error sige calificacion","calificacion incorrecta uttt","revisar calificacion","correccion calificacion"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('¿Cómo puedo reingresar después de una baja temporal?','Deberás participar en el proceso de reingreso por baja temporal durante el periodo establecido en la convocatoria oficial publicada por la universidad.','alumnos',true,
'["reingreso uttt","volver a estudiar despues baja","reingresar universidad","reingreso baja temporal","como regresar a la universidad","reingreso proceso uttt","volver a estudiar uttt","reingreso estudiantes","proceso reingreso universidad","reingresar carrera"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('Si quiero cambiar de carrera después de una baja, ¿qué debo hacer?','Deberás tramitar una baja definitiva y posteriormente realizar el proceso de solicitud de ficha para ingresar a la nueva carrera.','aspirantes',true,
'["cambiar carrera despues baja","nueva carrera despues baja","cambio carrera reingreso","quiero cambiar carrera despues baja","volver a inscribirme otra carrera","cambio carrera proceso nuevo ingreso","cambiar carrera universidad baja","nueva ficha carrera","cambio carrera desde cero","cambiar carrera despues salir"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  

INSERT INTO faqs (question, answer, category, is_active, variantes, nombre, puesto, unidadorganica) VALUES 
('Si mi plan de estudios cambió, ¿cómo puedo reingresar?','Deberás solicitar un proceso de equivalencia debido a la actualización del plan de estudios, con lo cual se determinará el cuatrimestre al que podrás reincorporarte.','alumnos',true,
'["plan estudios cambio","equivalencia plan estudios","reingreso plan nuevo","cambio plan estudios que hago","equivalencia materias plan nuevo","plan estudios actualizado","reingresar con plan nuevo","equivalencia universidad plan","cambio plan carrera","plan estudios diferente reingreso"]'::jsonb,
'Verónica Cruz Rico','Jefa de departamento','Departamento de Servicios Estudiantiles');  